### ISSUE TITLE
Apparently AppConfiguration.new must receive one parameter

### ISSUE THREAD

**Issue by sbalay** [guidomb/app_configuration#2]
Trying to instantiate AppConfiguration in the rails console fails with the following error:

irb(main):001:0> AppConfiguration.new
ArgumentError: wrong number of arguments (0 for 1)
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/app_configuration-0.0.2/lib/app_configuration.rb:9:in `new'
	from (irb):1
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'

**Comment by guidomb** [comment]
I have just checked the documentation and it is wrong  because you actually need to pass an argument. You need to provide the name of the config file.

**Comment by guidomb** [comment]
OK after reading the code (it's been while since I wrote this) the `AppConfiguration.new` should work without passing the argument, the documentation was correct.
